import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/provider/ThemeProvider";
import { Header } from "@/components/Header";
import { SideBar } from "@/components/SideBar";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"], // Specify the weights you need
  subsets: ["latin"], // Specify the subsets you need
});

export const metadata: Metadata = {
  title: "yd108",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} dark:bg-stone-800`}>
        <ThemeProvider 
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Header/>
          <div className=" flex  gap-2">
            <div className="w-[30%] relative">
            <SideBar/>
            </div>
            <div className="w-full pr-8 ">
            {children}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
